<a href="https://colab.research.google.com/github/arpitgotmare9-sudo/Simple_ANN_mini_project/blob/main/aan_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("/content/ai4i2020.csv")

In [3]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [8]:
df['TWF'].value_counts()

TWF
0    9954
1      46
Name: count, dtype: int64

In [9]:
df.isnull().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [10]:
df['Type'].unique()

array(['M', 'L', 'H'], dtype=object)

In [16]:
df.drop(columns=['Product ID'],inplace=True)

In [17]:
df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [19]:
df['Air temperature [K]'].unique()

array([298.1, 298.2, 298.3, 298.5, 298.4, 298.6, 298.7, 298.8, 298.9,
       299. , 299.1, 298. , 297.9, 297.8, 297.7, 297.6, 297.5, 297.4,
       297.3, 297.2, 297.1, 297. , 296.9, 296.8, 296.7, 296.6, 296.5,
       296.3, 296.4, 296.2, 296.1, 296. , 295.9, 295.8, 295.7, 295.6,
       295.5, 295.4, 295.3, 299.2, 299.3, 299.5, 299.4, 299.6, 299.7,
       299.8, 299.9, 300. , 300.1, 300.2, 300.3, 300.4, 300.5, 300.6,
       300.7, 300.8, 300.9, 301. , 301.1, 301.2, 301.3, 301.4, 301.5,
       301.6, 301.7, 301.8, 301.9, 302. , 302.1, 302.2, 302.3, 302.4,
       302.5, 302.6, 302.7, 302.8, 302.9, 303. , 303.1, 303.2, 303.3,
       303.4, 303.5, 303.6, 303.7, 303.8, 303.9, 304. , 304.1, 304.2,
       304.3, 304.4, 304.5])

In [20]:
df['Tool wear [min]'].unique()

array([  0,   3,   5,   7,   9,  11,  14,  16,  18,  21,  24,  29,  34,
        37,  40,  42,  44,  47,  50,  55,  58,  63,  65,  68,  70,  73,
        75,  77,  82,  84,  86,  89,  91,  93,  95,  98, 101, 104, 106,
       111, 113, 115, 117, 120, 125, 128, 130, 133, 135, 140, 143, 145,
       147, 152, 154, 156, 158, 160, 162, 165, 167, 169, 172, 174, 177,
       179, 181, 184, 189, 191, 193, 196, 198, 200, 202, 204, 206, 208,
         2,   4,  13,  15,  17,  20,  25,  27,  30,  33,  35,  53,  57,
        59,  61,  66,  72,  80,  92,  97,  99, 103, 108, 110, 112, 114,
       116, 118, 122, 124, 126, 132, 138, 148, 150, 155, 157, 159, 161,
       164, 186, 188, 194, 203, 211, 214, 216, 218,   8,  10,  22,  32,
        39,  41,  43,  45,  49,  54,  67,  69,  74,  76,  81,  96, 105,
       107, 119, 137, 142, 144, 146, 151, 153, 166, 168, 170, 173, 175,
       183, 185, 190, 195, 197, 209, 212,  19,  51,  56,  78,  83,  85,
        88,  90,  94, 109, 131, 134, 136, 192, 199, 201, 205, 210, 215,
        48,  71,  79, 123, 127, 129, 141, 176, 178, 180, 182, 207, 213,
        28, 139, 163, 171, 221,   6,  26,  46,  60, 100, 121, 220, 222,
       224, 229, 231, 233, 235, 240,  31,  38, 187,  12,  23,  62,  64,
        87, 217, 219, 227, 236, 238, 102, 149,  36, 223, 226, 228, 230,
       225,  52, 242, 244, 246, 232, 234, 237, 239, 241, 251, 253])

In [22]:
df['Machine failure'].value_counts()

Machine failure
0    9661
1     339
Name: count, dtype: int64

In [30]:
df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,M,298.1,308.6,1551,42.8,0,0
1,L,298.2,308.7,1408,46.3,3,0
2,L,298.1,308.5,1498,49.4,5,0
3,L,298.2,308.6,1433,39.5,7,0
4,L,298.2,308.7,1408,40.0,9,0

In [26]:
df.drop(columns=['TWF','HDF','PWF','OSF','RNF'],inplace=True)

In [27]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [28]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['Machine failure']),df['Machine failure'],test_size=0.2,random_state=42)

In [36]:
trf=ColumnTransformer(transformers=[
    ('onehot',OneHotEncoder(drop='first'),['Type']),
    ('scaling',StandardScaler(),['Air temperature [K]','Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]'])
],remainder='passthrough')

In [39]:
x_train_encode=trf.fit_transform(x_train)
x_test_encode=trf.transform(x_test)

In [43]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.metrics import Accuracy
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dropout

In [52]:
model=Sequential()
model.add(Dense(128,activation='relu',input_dim=7))
model.add(Dropout(0.2))
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [53]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 128)            │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34,177 (133.50 KB)

 Trainable params: 34,177 (133.50 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
adam=Adam(learning_rate=0.0001)
model.compile(optimizer=adam,loss=BinaryCrossentropy(),metrics=['accuracy'])

In [57]:
callback=EarlyStopping(monitor='val_loss',patience=10,verbose=1,mode='auto',restore_best_weights=True)

In [58]:
history=model.fit(x_train_encode,y_train,epochs=500,validation_data=(x_test_encode,y_test),callbacks=callback)

Epoch 1/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9794 - loss: 0.0586 - val_accuracy: 0.9820 - val_loss: 0.0570
Epoch 2/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9816 - loss: 0.0556 - val_accuracy: 0.9815 - val_loss: 0.0561
Epoch 3/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9814 - loss: 0.0547 - val_accuracy: 0.9835 - val_loss: 0.0565
Epoch 4/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9808 - loss: 0.0551 - val_accuracy: 0.9815 - val_loss: 0.0567
Epoch 5/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9818 - loss: 0.0535 - val_accuracy: 0.9815 - val_loss: 0.0563
Epoch 6/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9799 - loss: 0.0569 - val_accuracy: 0.9840 - val_loss: 0.0557
Epoch 7/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9821 - loss: 0.0552 - val_accuracy: 0.9855 - val_loss: 0.0553
Epoch 8/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9790 - loss: 0.0561 - val_accuracy: 0.9845 - val_loss: 0.0554
Epoch 9/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9815 - loss: 0.0538 - val_accuracy: 0.9810 - val_loss: 0.0562
Epoch 10/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9825 - loss: 0.0556 - val_accuracy: 0.9840 - val_loss: 0.0545
Epoch 11/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9810 - loss: 0.0547 - val_accuracy: 0.9825 - val_loss: 0.0558
Epoch 12/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9822 - loss: 0.0526 - val_accuracy: 0.9815 - val_loss: 0.0562
Epoch 13/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9837 - loss: 0.0550 - val_accuracy: 0.9840 - val_loss: 0.0554
Epoch 14/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9824 - loss: 0.0517 - val_accuracy: 0.9830 - val_loss: 0.0560
Epoch 15/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9835 - loss: 0.0529 - val_accuracy: 0.9840 - val_loss: 0.0554
Epoch 16/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9824 - loss: 0.0547 - val_accuracy: 0.9835 - val_loss: 0.0556
Epoch 17/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9821 - loss: 0.0534 - val_accuracy: 0.9820 - val_loss: 0.0568
Epoch 18/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9820 - loss: 0.0558 - val_accuracy: 0.9845 - val_loss: 0.0558
Epoch 19/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9818 - loss: 0.0539 - val_accuracy: 0.9835 - val_loss: 0.0565
Epoch 20/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9825 - loss: 0.0517 - val_accuracy: 0.9840 - val_loss: 0.0561
Epoch 20: early stopping
Restoring model weights from the end of the best epoch: 10.

In [129]:
new_machine = pd.DataFrame([{
    "Air temperature [K]": 300.0,
    "Process temperature [K]": 310.0,
    "Rotational speed [rpm]": 1500,
    "Torque [Nm]": 40.0,
    "Tool wear [min]": 100,
    "Type":'L'
}])

In [130]:
y_pread=model.predict(trf.transform(new_machine))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

In [131]:
def predict(y_pread):
  if(y_pread>0.5):
    print("Machine will fail")
    print(f"probablity : {y_pread[0][0]:.2%}")
  else:
    print("Machine will not fail")
    print(f"probablity : {y_pread[0][0]:.2%}")

In [132]:
predict(y_pread)

Machine will not fail
probablity : 0.02%